# Generated by Django 5.0 on 2023-12-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_supervision', '0002_alter_student_legalstatus_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(default=0, max_length=15)),
                ('supervis_id', models.IntegerField(default=0, max_length=15)),
                ('faculty', models.CharField(default=None, max_length=15)),
                ('institue', models.CharField(default=None, max_length=15)),
                ('department', models.CharField(default=None, max_length=15)),
                ('sub_year', models.CharField(default=None, max_length=15)),
                ('def_year', models.CharField(default=None, max_length=15)),
                ('def_grade', models.CharField(default=None, max_length=15)),
            ],
        ),
    ]
