# Generated by Django 5.0 on 2023-12-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_supervision', '0003_dissertation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('diploma_no', models.IntegerField(max_length=25)),
                ('graduating_sem', models.IntegerField(max_length=25)),
                ('starting_sem', models.IntegerField(max_length=25)),
                ('faculty_otm', models.CharField(max_length=25)),
                ('std_university_id', models.CharField(max_length=25)),
                ('supervisor_id', models.CharField(max_length=25)),
            ],
        ),
    ]
