# Generated by Django 5.0 on 2023-12-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_supervision', '0004_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='title',
            field=models.IntegerField(default=0, max_length=15),
        ),
    ]
